export const routes = [
  { label: "New In", to: "/new-in" },
  { label: "Shop", to: "/shop" },
  { label: "Collections", to: "/collections" },
  { label: "Lookbook", to: "/lookbook" },
  { label: "Our Story", to: "/our-story" },
];

export const products = [
  {
    id: "ivory-wrap-dress",
    name: "Ivory Wrap Dress",
    price: "PKR 18,500",
    oldPrice: "PKR 22,000",
    label: "New",
    category: "Dresses",
    descriptor: "Soft ivory drape",
    image: "https://images.pexels.com/photos/13776795/pexels-photo-13776795.jpeg?auto=compress&cs=tinysrgb&w=900",
    alt: "Ivory wrap dress styled in soft neutral studio light",
  },
  {
    id: "noir-evening-set",
    name: "Noir Evening Set",
    price: "PKR 24,000",
    oldPrice: "PKR 28,500",
    label: "Limited",
    category: "Occasion",
    descriptor: "Evening separates",
    image: "https://images.pexels.com/photos/19401640/pexels-photo-19401640/free-photo-of-studio-shot-of-model-in-beige-dress.jpeg?auto=compress&cs=tinysrgb&w=900",
    alt: "Evening set styled in a refined beige studio setting",
  },
  {
    id: "soft-sand-kurta",
    name: "Soft Sand Kurta",
    price: "PKR 14,800",
    oldPrice: "PKR 17,200",
    label: "New",
    category: "Kurtas",
    descriptor: "Everyday ease",
    image: "https://images.pexels.com/photos/28895909/pexels-photo-28895909/free-photo-of-elegant-woman-in-beige-dress-outdoors.jpeg?auto=compress&cs=tinysrgb&w=900",
    alt: "Soft sand kurta styled with warm neutral elegance",
  },
  {
    id: "pearl-detail-ensemble",
    name: "Pearl Detail Ensemble",
    price: "PKR 21,500",
    oldPrice: "PKR 25,500",
    label: "Signature",
    category: "Co-ords",
    descriptor: "Pearl detail finish",
    image: "https://images.pexels.com/photos/13816069/pexels-photo-13816069.jpeg?auto=compress&cs=tinysrgb&w=900",
    alt: "Pearl detail ensemble styled in a clean beige studio setting",
  },
  {
    id: "ivory-day-dress",
    name: "Ivory Day Dress",
    price: "PKR 17,200",
    oldPrice: "PKR 20,000",
    label: "New",
    category: "Dresses",
    descriptor: "Light day silhouette",
    image: "https://images.pexels.com/photos/31649583/pexels-photo-31649583.jpeg?auto=compress&cs=tinysrgb&w=900",
    alt: "Ivory day dress with soft feminine detail",
  },
  {
    id: "stone-mini-dress",
    name: "Stone Mini Dress",
    price: "PKR 15,900",
    oldPrice: "PKR 18,000",
    label: "New",
    category: "Dresses",
    descriptor: "Clean mini shape",
    image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=85",
    alt: "Refined stone mini dress detail in warm light",
  },
  {
    id: "sand-pleat-separate",
    name: "Sand Pleat Separate",
    price: "PKR 13,600",
    label: "Essential",
    category: "Essentials",
    descriptor: "Pleated separate",
    image: "https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=85",
    alt: "Sand pleat separate styled with refined fabric detail",
  },
  {
    id: "pearl-trim-layer",
    name: "Pearl Trim Layer",
    price: "PKR 16,400",
    label: "Signature",
    category: "Essentials",
    descriptor: "Layered finish",
    image: "https://images.pexels.com/photos/13776795/pexels-photo-13776795.jpeg?auto=compress&cs=tinysrgb&w=900",
    alt: "Pearl trim layer in soft ivory styling",
  },
  {
    id: "moonlit-gather-dress",
    name: "Moonlit Gather Dress",
    price: "PKR 22,800",
    label: "Occasion",
    category: "Occasion",
    descriptor: "Gathered formal shape",
    image: "https://images.pexels.com/photos/19401640/pexels-photo-19401640/free-photo-of-studio-shot-of-model-in-beige-dress.jpeg?auto=compress&cs=tinysrgb&w=900",
    alt: "Moonlit gathered dress styled for occasion wear",
  },
  {
    id: "champagne-column-set",
    name: "Champagne Column Set",
    price: "PKR 26,000",
    label: "Limited",
    category: "Co-ords",
    descriptor: "Column co-ord set",
    image: "https://images.pexels.com/photos/13816069/pexels-photo-13816069.jpeg?auto=compress&cs=tinysrgb&w=900",
    alt: "Champagne column set in neutral studio styling",
  },
  {
    id: "ivory-ease-tunic",
    name: "Ivory Ease Tunic",
    price: "PKR 12,900",
    label: "Essential",
    category: "Kurtas",
    descriptor: "Relaxed tunic",
    image: "https://images.pexels.com/photos/28895909/pexels-photo-28895909/free-photo-of-elegant-woman-in-beige-dress-outdoors.jpeg?auto=compress&cs=tinysrgb&w=900",
    alt: "Ivory ease tunic in warm outdoor styling",
  },
  {
    id: "sand-drape-ensemble",
    name: "Sand Drape Ensemble",
    price: "PKR 19,700",
    label: "Signature",
    category: "Occasion",
    descriptor: "Soft draped ensemble",
    image: "https://images.pexels.com/photos/31649583/pexels-photo-31649583.jpeg?auto=compress&cs=tinysrgb&w=900",
    alt: "Sand drape ensemble with soft feminine detail",
  },
];

export const services = [
  { icon: "delivery", title: "Complimentary Delivery", text: "On qualifying orders" },
  { icon: "returns", title: "Easy Returns", text: "Simple 14-day returns" },
  { icon: "care", title: "Customer Care", text: "We're here when you need us" },
];

export const collections = [
  {
    title: "Occasion",
    text: "Pieces with presence for dinners, gatherings, and formal moments.",
    count: "18 pieces",
    image: "https://images.pexels.com/photos/19401640/pexels-photo-19401640/free-photo-of-studio-shot-of-model-in-beige-dress.jpeg?auto=compress&cs=tinysrgb&w=1200",
    alt: "Elegant occasion collection styled in a refined beige studio setting",
  },
  {
    title: "Everyday",
    text: "Easy forms and refined finishing for daily wear.",
    count: "24 pieces",
    image: "https://images.pexels.com/photos/28895909/pexels-photo-28895909/free-photo-of-elegant-woman-in-beige-dress-outdoors.jpeg?auto=compress&cs=tinysrgb&w=900",
    alt: "Everyday collection in warm neutral styling",
  },
  {
    title: "New Season",
    text: "The newest silhouettes and color stories in the Houmaah world.",
    count: "24 pieces",
    image: "/assets/houmaah-hero-banner.png",
    alt: "Houmaah new season tailored campaign",
    season: true,
  },
  {
    title: "Essentials",
    text: "Quiet staples designed to be worn often and styled easily.",
    count: "16 pieces",
    image: "https://images.pexels.com/photos/13776795/pexels-photo-13776795.jpeg?auto=compress&cs=tinysrgb&w=900",
    alt: "Soft ivory essentials collection styling",
  },
  {
    title: "Soft Detail",
    text: "Delicate trims, gentle texture, and polished feminine finishes.",
    count: "12 pieces",
    image: "https://images.pexels.com/photos/31649583/pexels-photo-31649583.jpeg?auto=compress&cs=tinysrgb&w=900",
    alt: "Soft feminine collection with floral detail",
  },
];

export const journalPosts = [
  {
    title: "How to Build a Quiet Occasion Wardrobe",
    date: "September 2026",
    excerpt: "A short guide to choosing fewer pieces with more presence, from soft tailoring to delicate finishing.",
  },
  {
    title: "Fabric Care for Refined Everyday Pieces",
    date: "August 2026",
    excerpt: "Simple habits for keeping ivory, sand, and pearl-toned garments looking composed between wears.",
  },
  {
    title: "The Houmaah Approach to Timeless Essentials",
    date: "July 2026",
    excerpt: "Why clean silhouettes, considered length, and gentle texture shape the core of the wardrobe.",
  },
];
